### ISSUE TITLE
Create api endpoint for APPLE consumption

### ISSUE THREAD

**Issue by JustAman62** [BrownKnight/STRUDEL#14]
Final data format to be confirmed by @benjaminjellis. Firstly, a csv-formatted table of fixtures for a given date range should be provided. This is the endpoint that will be used to provide data for the prediction engine itself.

For analytics purposes, an endpoint that outputs all the prediction data for any fixture within the given date range should be provided.

**Comment by benjaminjellis** [comment]
APPLE ingests fixtures to predict using a file that looks like https://github.com/benjaminjellis/APPLE/blob/master/data/user_predictions/20_21/week2/week2userpredictions.csv

APPLE doesn't require user prediction data in this file, it only ingests the fixtures to predict for. There are additional analytics that are shared that require the whole data file above. For simplicity though the same file is used by both APPLE to make predictions and by the analytics components to aggregate and asses winners for each round.

**Comment by JustAman62** [comment]
Some changes to the exact data fetched using the /iapi//predictions/bydate endpoint may need to be adjusted to accommodate APPLE requirements, but this can be figured out in another issue down the road.
