### ISSUE TITLE
Update /iapi/predictions schema to accept APPLE prediction probabilities 

### ISSUE THREAD

**Issue by benjaminjellis** [BrownKnight/STRUDEL#38]
APPLE output to file looks like this https://github.com/benjaminjellis/APPLE/blob/master/results/20_21/week6/7640a728-04fb-11eb-8c32-acde48001122_predicted_results.csv

The GET /iapi/predictions endpoint needs to be updated to include fields for p(H), p(D) and p(A)

**Comment by JustAman62** [comment]
PR #39 implements this functionality.

predictions can be uploaded to the `/iapi/predictions` PUT endpoint with the following schema:
```json
{
  "prediction": "H|D|A",
  "homeWinProbability": 0.0,
  "drawProbability": 0.0,
  "awayWinProbability": 0.0,
  "fixture": {
    "id": <fixtureID>,
  },
  "user": {
     "id": <userID>
   }
}
```

Also note that predictions currently need to be uploaded one at a time
