### ISSUE TITLE
Define ENKEL endpoint to return full aggregated user predictions, APPLE predictions, and results

### ISSUE THREAD

**Issue by benjaminjellis** [BrownKnight/STRUDEL#40]
The endpoint should return all:

- user predictions
- APPLE predictions 
- full time results 

For all fixtures up to a specified date. 

We'll need to discuss how to deal with a request for a date that would mean a return of fixtures for which there's no full time result. 

Ideally the return would be in csv format like this https://github.com/benjaminjellis/APPLE/blob/master/data/aggregated_results/20_21/predictions_and_results_log.csv

This will also require migration of the above aggregated data. 

This is a blocker to moving APPLE to AWS.

**Comment by JustAman62** [comment]
Full time results added as a column to the csv, named FTR. If none of the fixtures returned have a result, the column will still exist, but the field will be empty for each row.

If there is a mix of fixtures that do/do not have results, the rows that do now have results will be empty.

Need to figure out a clean way to import those existing predictions

**Comment by benjaminjellis** [comment]
https://beatthebot.co.uk/iapi/fixtures/bydate?startDate=2020-10-22&endDate=2020-10-29&format=csv 
The above endpoint does not return FTR column

Additionally, Strudel doesn't group fixtures by week number. Week number is an arbitrary concept and while it's not explicit in Strudel it is implicit as it defines how we batch together predictions for people to make. 

APPLE requires week number for aggregation of historical data which is then used for analytics so it's important that this information is contained in Strudel for APPLE to be migrated. We can tackle this at the same time we tackle migrating historical data to Strudel.

**Comment by JustAman62** [comment]
Week number has been added to the Fixture Entity, and a script written by Ben has migrated all historical predictions to STRUDEL. I believe there's nothing else left to be done
